configName: sam_e51_cnano
folderName: ''
format_version: v1.0
frameworkPath: ../../Harmony3
processor: ATSAME51J20A
projectName: ''
settings:
  PackageFilter: csp;csp_apps_sam_d5x_e5x;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAME51_DFP\3.4.98\atdf\ATSAME51J20A.atdf
